#ifndef FOX_LEVELS
#define FOX_LEVELS

#include "../HeaderFiles/StartSlides.h"
#include "../HeaderFiles/MainMenu.h"
#include "../HeaderFiles/TestLevel.h"
#include "../HeaderFiles/LevelShowcase.h"
#include "../HeaderFiles/TutorialLevel.h"
#include "../HeaderFiles/MapLevel.h"
#include "../HeaderFiles/EPMenu.h"
#include "../HeaderFiles/EP1Slides.h"
#include "../HeaderFiles/EP2Slides.h"
#include "../HeaderFiles/Level1.h"
#include "../HeaderFiles/ArmGuy.h"
#include "../HeaderFiles/Level2.h"
#include "../HeaderFiles/HandGuy.h"
#include "../HeaderFiles/Level3.h"
#include "../HeaderFiles/Level3.1.h"
#include "../HeaderFiles/YeahGuy.h"
#include "../HeaderFiles/Level4.h"
#include "../HeaderFiles/Kevin.h"
#include "../HeaderFiles/CharacterSelect.h"
#include "../HeaderFiles/DevMenu.h"
#include "../HeaderFiles/OptionsMenu.h"
#include "../HeaderFiles/Shop1.h"
#include "../HeaderFiles/Shop2.h"
#include "../HeaderFiles/Shop3.h"
#include "../HeaderFiles/Shop4.h"
#include "../HeaderFiles/Level5.h"
#include "../HeaderFiles/Level6.h"
#include "../HeaderFiles/Level7.h"
#include "../HeaderFiles/Credits.h"

#endif